import { Geist, Geist_Mono } from "next/font/google";



import "./globals.css";
import CustomNavbar from "@/components/CustomNavbar";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App ankits",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 
   
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
         <CustomNavbar/>
        
        
        <div>{children}</div>
        <Footer/>
       
      </body>
    </html>

  );
}
